# Generated by Django 6.0.1 on 2026-01-18 23:03
import django.core.validators
import django.db.models.functions.text
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.F("id"), models.F("id")
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("name", models.CharField()),
                ("iae_code", models.CharField()),
                ("rentability", models.IntegerField()),
                (
                    "typology",
                    models.FloatField(
                        validators=[
                            django.core.validators.MaxValueValidator(1.0),
                            django.core.validators.MinValueValidator(0.0),
                        ]
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="IAE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("description", models.TextField()),
            ],
        ),
    ]
