# Generated by Django 6.0.1 on 2026-01-20 16:38
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="IAE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("group", models.CharField()),
                ("value", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Value("BIZ-"), models.F("id")
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("name", models.CharField()),
                ("rentability", models.IntegerField()),
                ("distance_to_the_city_center", models.IntegerField()),
                ("conversion_rate", models.FloatField(blank=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
                ),
                (
                    "iae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="businesses",
                        to="business.iae",
                    ),
                ),
            ],
        ),
    ]
